# Generated by Django 4.2.20 on 2025-05-07 19:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0002_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
