# Generated by Django 5.2 on 2025-04-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0003_servicealert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicealert',
            options={},
        ),
        migrations.RemoveField(
            model_name='servicealert',
            name='affected_stations',
        ),
        migrations.RemoveField(
            model_name='servicealert',
            name='alternative_routes',
        ),
        migrations.RemoveField(
            model_name='servicealert',
            name='estimated_duration',
        ),
        migrations.RemoveField(
            model_name='servicealert',
            name='is_active',
        ),
        migrations.AddField(
            model_name='servicealert',
            name='alert_type',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('emergency', 'Emergency'), ('maintenance', 'Maintenance')], default='info', max_length=50),
        ),
        migrations.AddField(
            model_name='servicealert',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='servicealert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicealert',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
