# Generated by Django 4.2.20 on 2025-05-07 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0004_medicalhelp_medicalhelpsolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhelp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_helps', to=settings.AUTH_USER_MODEL),
        ),
    ]
