# Generated by Django 4.2.20 on 2025-04-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0004_alter_servicealert_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicealert',
            name='alert_type',
        ),
        migrations.RemoveField(
            model_name='servicealert',
            name='status',
        ),
        migrations.RemoveField(
            model_name='servicealert',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='servicealert',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicealert',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
