# Generated by Django 4.2.20 on 2025-04-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0005_remove_servicealert_alert_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicealert',
            name='affected_stations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicealert',
            name='alternative_routes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicealert',
            name='estimated_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
