# Generated by Django 4.2.20 on 2025-05-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0008_alter_quizresult_score_alter_quizresult_total'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quizresult',
            table='Quiz result',
        ),
    ]
