# Generated by Django 4.2.20 on 2025-05-07 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0009_alter_quizresult_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quizresult',
            table='Quiz results',
        ),
    ]
