# Generated by Django 4.2.20 on 2025-05-06 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0006_servicealert_affected_stations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicealert',
            name='affected_stations',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicealert',
            name='alternative_routes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicealert',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicealert',
            name='estimated_duration',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
