# Generated by Django 4.2.20 on 2025-05-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0007_alter_quizresult_score_alter_quizresult_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='total',
            field=models.IntegerField(),
        ),
    ]
